// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel arrival_cel000[] = {
    /* Len */ 3,
    /* 000 */ 0x40f7, 0x81ca, 0x1000,
    /* 001 */ 0x40f7, 0x801a, 0x1004,
    /* 002 */ 0x00f8, 0x41b6, 0x1008
};

AnimationCel arrival_cel001[] = {
    /* Len */ 3,
    /* 000 */ 0x40f7, 0x81ca, 0x1000,
    /* 001 */ 0x40f7, 0x801a, 0x1004,
    /* 002 */ 0x00f7, 0x41b6, 0x1008
};

AnimationCel arrival_cel002[] = {
    /* Len */ 3,
    /* 000 */ 0x40f7, 0x81ca, 0x1000,
    /* 001 */ 0x40f7, 0x801a, 0x1004,
    /* 002 */ 0x00f9, 0x41b6, 0x1008
};

AnimationCel arrival_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x40f7, 0x81ca, 0x1000,
    /* 001 */ 0x40f7, 0x801a, 0x1004,
    /* 002 */ 0x00f8, 0x4006, 0x1008
};

AnimationCel arrival_cel004[] = {
    /* Len */ 3,
    /* 000 */ 0x40f7, 0x81ca, 0x1000,
    /* 001 */ 0x40f7, 0x801a, 0x1004,
    /* 002 */ 0x00f7, 0x4006, 0x1008
};

AnimationCel arrival_cel005[] = {
    /* Len */ 3,
    /* 000 */ 0x40f7, 0x81ca, 0x1000,
    /* 001 */ 0x40f7, 0x801a, 0x1004,
    /* 002 */ 0x00f9, 0x4006, 0x1008
};

