// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel polyrhythm_2_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x0018
};

AnimationCel polyrhythm_2_prologue_cel001[] = {
    /* Len */ 5,
    /* 000 */ 0x00d0, 0x81dd, 0x1058,
    /* 001 */ 0x00d0, 0x81fd, 0x105c,
    /* 002 */ 0x00d0, 0xc1c0, 0x0008,
    /* 003 */ 0x00d0, 0xc000, 0x0010,
    /* 004 */ 0x00d0, 0xc040, 0x0000
};

